#ifndef __CFG_USER_H__
#define __CFG_USER_H__

enum {
    THREAD_PRIO_SYS_RUNNING = 1,
    THREAD_PRIO_TEST_LUAPARSER,
    THREAD_PRIO_TEST_FATFS,
    THREAD_PRIO_TEST_UIP,
    THREAD_PRIO_DRIVER_ETH
};

enum {
    ISR_PRIO_SYSTICK = 1,
    ISR_PRIO_OTHER,
    ISR_PRIO_PENDSV
};

#define ISR_PRIO_ARCH_MEM  ISR_PRIO_OTHER
#define ISR_PRIO_DISK      ISR_PRIO_OTHER
#define ISR_PRIO_ETH       ISR_PRIO_OTHER
#define ISR_PRIO_DEV_USART ISR_PRIO_OTHER
#define ISR_PRIO_TTY_USART ISR_PRIO_OTHER

#define SYS_RUNNING_INTERVAL_MSECS (500)
#define MAD_OS_STACK_SIZE          (4 * 1024)
// #define MAD_OS_STACK_SIZE          (4608)

#endif
