#ifndef __CFG_USER_H__
#define __CFG_USER_H__

enum {
    THREAD_PRIO_SYS_RUNNING = 1,
    THREAD_PRIO_BLE,
    THREAD_PRIO_KEY,
    THREAD_PRIO_MAIN
};

enum {
    ISR_PRIO_SYSTICK = 1,
    ISR_PRIO_OTHER,
    ISR_PRIO_PENDSV
};

#define ISR_PRIO_ARCH_MEM  ISR_PRIO_OTHER
#define ISR_PRIO_BLE_USART ISR_PRIO_OTHER
#define ISR_PRIO_TTY_USART ISR_PRIO_OTHER

#define SYS_RUNNING_INTERVAL_MSECS (500)
#define MAD_OS_STACK_SIZE          (5 * 1024)

#endif
